package com.meiming.crm.settings.mapper;

import com.meiming.crm.settings.domain.DicType;

import java.util.Dictionary;
import java.util.List;

public interface DicTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Mon May 18 16:01:30 CST 2020
     */
    int deleteByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Mon May 18 16:01:30 CST 2020
     */
    int insert(DicType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Mon May 18 16:01:30 CST 2020
     */
    int insertSelective(DicType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Mon May 18 16:01:30 CST 2020
     */
    DicType selectByPrimaryKey(String code);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Mon May 18 16:01:30 CST 2020
     */
    int updateByPrimaryKeySelective(DicType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_dic_type
     *
     * @mbggenerated Mon May 18 16:01:30 CST 2020
     */
    int updateByPrimaryKey(DicType record);

    //查询所有的字典类型
    List<DicType> selectAllDicTypes();

    //保存创建的数据字典类型
    int insertDicType(DicType dicType);

    //根据code查询所对应字典类型
    DicType selectDicTypeByCode(String code);

    //更新数据字典类型
    int updateDicType(DicType dicType);

    //根据codes来批量删除字典类型
    int deleteDicTypeCodes(String[] codes); //codes数组code
}

